# Generated by Django 4.0 on 2023-03-09 07:54

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='名称')),
                ('path', models.CharField(blank=True, max_length=200, null=True, verbose_name='链接地址')),
                ('icon', models.SlugField(blank=True, help_text='<a target="_blank" href="https://feathericons.com/">图标库</a>', null=True, verbose_name='图标')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('groups', models.ManyToManyField(blank=True, related_name='juss_menus', to='auth.Group', verbose_name='授权分组')),
                ('model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype', verbose_name='APP模型')),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='juss.menu', verbose_name='上级菜单')),
            ],
            options={
                'verbose_name': '后台菜单',
                'verbose_name_plural': '后台菜单',
            },
        ),
    ]
