# Generated by Django 4.0 on 2023-03-09 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('juss', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu',
            old_name='model',
            new_name='content_type',
        ),
    ]
